apiVersion: v1
kind: Secret
metadata:
  name: {{ include "deltallm.fullname" . }}
  labels:
    {{- include "deltallm.labels" . | nindent 4 }}
type: Opaque
stringData:
  master-key: {{ required "config.masterKey is required" .Values.config.masterKey | quote }}
